name: Build & publish binary node

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          # - 10 # Issue with gyp build can build with this version.
          # - 12
          # - 14
          - 16
          - 18
        include:
          - os: windows-latest
            node: 18
            host: x86
            target: x86

    name: ${{ matrix.os }} (node=${{ matrix.node }}, host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{ matrix.target }}

      - name: Setup node (node=${{ matrix.node }}, host=${{ matrix.host }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{github.actor}}"
      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV
          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi
      - name: Configure build
        run: yarn node-pre-gyp configure --target_arch=${{ env.TARGET }}

      - name: Build binaries
        run: yarn node-pre-gyp build --target_arch=${{ env.TARGET }}

      - name: Package prebuilt binaries
        run: yarn node-pre-gyp package --target_arch=${{ env.TARGET }}

      # Run only for matrix.node 18
      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node == 18
        with:
          name: prebuilt-binaries
          path: build/stage/*/*
          retention-days: 7

      # - name: Set git config
      #   if: matrix.node == 18 && startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     git config user.email "${{github.actor}}"
      #     git config user.name "${{github.actor}}@users.noreply.github.com"

      # - name: Set package version to ${{ github.event.release.tag_name }}
      #   if: matrix.node == 18 && startsWith(github.ref, 'refs/tags/')
      #   run: npm version ${{ github.event.release.tag_name }}

      # Run only for matrix.node 18
      - name: Upload binaries to GitHub Release
        run: yarn node-pre-gyp-github publish
        if: matrix.node == 18 && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}

  publish:
    needs: [ build ]
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{github.actor}}"
      - run: npm install --ignore-scripts
      - run: npm run build:macos
      - run: npm run test-ci
      # - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish